config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions


  get 'dashboard/default'
  root to: 'dashboard#default'
  resources :inventories do
   resources :versions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_paper_trail :ignore => [:created_at, :updated_at],
                  :on     => [:update, :destroy]
end

app/models/user.rb
require 'net/ldap'

class User
        include ActiveModel::Model

  attr_accessor :username, :password
  def initialize(attributes={})
    super
  end
  ATTR_SV = {
              :login => :samaccountname,
              :first_name => :givenname,
              :last_name => :sn,
              :email => :mail
            }

  ATTR_MV = {
              :groups => [ :memberof,
                           # Get the simplified name of first-level groups.
                           # TODO: Handle escaped special characters
                           Proc.new {|g| g.sub(/.*?CN=(.*?),.*/, '\1')} ]
            }

        def self.find(username)
                #TODO: figure out how to pull more info from AD in the first place
                usr = self.new
        usr.username = username
                return usr
        end

        def self.authenticate(username, password)
                #do active directory stuff here
                conn = Net::LDAP.new :host => APP_CONFIG['ldap_server'],
                         :port => APP_CONFIG['ldap_port'],
                         :base => APP_CONFIG['ldap_base'],
                         :encryption => APP_CONFIG['ldap_encryption'].to_sym,
                         :auth => { :username => "#{username}@#{APP_CONFIG['ldap_domain']}",
                                    :password => "#{password}",
                                    :method => APP_CONFIG['ldap_connect_method'].to_sym }
      begin
            if conn.bind and user = conn.search(:filter => "sAMAccountName=#{username}").first
                      # TODO: Enable this for enumeration of user data.
                      # self.populate_user_data(user)
                      usr = self.new
                      usr.username = user.name[0].to_s
                      return usr
                    else
                      return false
                    end
      rescue Exception => e
        puts e.to_yaml
            return false
                  end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_paper_trail_whodunnit

        def current_user
          @current_user ||= User.find(session[:username]) if session[:username]
        end
        helper_method :current_user

        def user_for_paper_trail
           if session[:username].nil?
              'Public user'
           else
              current_user.username
          end  # or whatever
        end
        def authorize
          if current_user.nil?
                session[:params] = params if params
          else
                session[:params] = nil
          end
          redirect_to login_url, alert: "Not authorized" if current_user.nil?
        end

        def four_oh_four
                flash[:notice] = "Resource not found"
                render "welcome/index"
        end

        def clean_params(params)
                newparams = Hash.new
                ignore_params = ['format','controller','action','id', 'Id']
                params.each do |key, val|
                  unless ignore_params.include? key
                    newparams[key] = val
                  end
                end
                newparams
        end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #before_filter :authorize
  def default
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  #before_filter :authorize

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:id, :contract, :room, :updated_at, :created_at, :AssetTag, :Model, :Serial, :Description, :Location, :POC, :Disposition, :Win7, :Office, :Access, :Visio, :Project)
    end
end

class VersionsController < InventoriesController
  def index
    @versions = Inventory.find(params[:inventory_id]).versions.reverse
    respond_to do |format|
      format.json { render :layout =>  false, :json => @versions.to_json() }
    end
  end
  private
  def versions_params
    params.require(:inventory_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
        def new
        end

        def create
          if user = User.authenticate(params[:username], params[:password])
            session[:username] = user.username
            if session[:params]
                session[:params].symbolize_keys!
                redirect_to :controller => session[:params][:controller], :action => session[:params][:action], :params => session[:params], notice: "Logged in!"
            else
                redirect_to root_url, notice: "Logged in!"
            end
          else
            flash.now.alert = "Email or password is invalid"
            render "new"
          end
        end

        def destroy
          session[:username] = nil
          session[:params] = nil
          redirect_to root_url, notice: "Logged out!"
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/dashboard/default.html.erb
<%= render :partial => "shared/header" %>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-primary">
      <div class="panel-heading">Inventories</div>
      <div class="panel-body">
    <div id="filterbox">
        Search as you type:
        <input type="text" />
        <a><% image_url('search_icon.png') %></a>
    </div>
        <div id="inventories"></div>
        <script id="detailTemplate" type="text/x-shield-template">
        <table>
          <div id="inventoriesdetail"></div>
        </table>
       </script>
      </script>
      </div>
    </div>
  </div>
</div>
<%= render :partial => "shared/footer" %>

app/views/inventories/_form.html.erb
<%= form_for(inventory) do |f| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AssetTag %>
    <%= f.text_field :AssetTag %>
  </div>

  <div class="field">
    <%= f.label :Model %>
    <%= f.text_field :Model %>
  </div>

  <div class="field">
    <%= f.label :Serial %>
    <%= f.text_field :Serial %>
  </div>

  <div class="field">
    <%= f.label :Description %>
    <%= f.text_field :Description %>
  </div>

  <div class="field">
    <%= f.label :Location %>
    <%= f.text_field :Location %>
  </div>

  <div class="field">
    <%= f.label :POC %>
    <%= f.text_field :POC %>
  </div>

  <div class="field">
    <%= f.label :Disposition %>
    <%= f.text_area :Disposition %>
  </div>

  <div class="field">
    <%= f.label :Win7 %>
    <%= f.text_field :Win7 %>
  </div>

  <div class="field">
    <%= f.label :Office %>
    <%= f.text_field :Office %>
  </div>

  <div class="field">
    <%= f.label :Access %>
    <%= f.text_field :Access %>
  </div>

  <div class="field">
    <%= f.label :Visio %>
    <%= f.text_field :Visio %>
  </div>

  <div class="field">
    <%= f.label :Project %>
    <%= f.text_field :Project %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>ItemType</th>
      <th>item_id</th>
      <th>event</th>
      <th>created_at</th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |inventory| %>
      <tr>
        <td><%= inventory.id %></td>
        <td><%= inventory.item_type %></td>
        <td><%= inventory.item_id %></td>
        <td><%= inventory.event %></td>
        <td><%= inventory.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assettag:</strong>
  <%= @inventory.AssetTag %>
</p>

<p>
  <strong>Model:</strong>
  <%= @inventory.Model %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @inventory.Serial %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory.Description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @inventory.Location %>
</p>

<p>
  <strong>Poc:</strong>
  <%= @inventory.POC %>
</p>

<p>
  <strong>Disposition:</strong>
  <%= @inventory.Disposition %>
</p>

<p>
  <strong>Win7:</strong>
  <%= @inventory.Win7 %>
</p>

<p>
  <strong>Office:</strong>
  <%= @inventory.Office %>
</p>

<p>
  <strong>Access:</strong>
  <%= @inventory.Access %>
</p>

<p>
  <strong>Visio:</strong>
  <%= @inventory.Visio %>
</p>

<p>
  <strong>Project:</strong>
  <%= @inventory.Project %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShielduiGridRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'all.min.css',    media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//shieldui.com/shared/components/latest/js/shieldui-all.min.js', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>&copy; Black Hall Aerospace <%= Time.new.year %></p>
</div>

app/views/shared/_header.html.erb
<body class="theme-dark">
<div class="masthead">
        <div class="top">
                <h3 class="text-muted logo pull-left"><a href="/">BlackHall IT Portal</a></h3>
                <div class="nav nav-pills pull-right">
                        <li>
                        <% if current_user %>
                        Logged in as <%= current_user.username %> <%= link_to "Log Out", logout_path %>
                        <%= javascript_tag do %>
                           window.current_user = "<%= current_user.username %>";
                        <% end %>
                        <% else %>
                        <%= link_to "Log In", login_path %>
                        <%= javascript_tag do %>
                           window.current_user = "";
                        <% end %>
                        <% end %>
                        </li>
                </div>
        </div>
</div>